%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /home/atomic/git/COGS109_Final/scripts/Wealth_Accounting.xlsx
%    Worksheet: Data
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/11/25 18:42:40

%% Import the data
[~, ~, WealthAccounting] = xlsread('Wealth_Accounting.xlsx','Data');
WealthAccounting = WealthAccounting(2:end,1:4);
WealthAccounting(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),WealthAccounting)) = {''};


% Auto-generated by MATLAB on 2016/11/25 18:43:34

%% Import the data
[~, ~, raw] = xlsread('Wealth_Accounting.xlsx','Data');
raw = raw(2:end,5:end);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));


%% Clear temporary variables
% clearvars data raw R;

year = [1970:2014];

    