%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /home/atomic/git/COGS109_Final/scripts/total_and_per_capita_wealth_of_nations.xlsx
%    Worksheet: total wealth, 1995
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/11/25 12:01:14

clear all;
%% Import the data
[~, ~, raw] = xlsread('total_and_per_capita_wealth_of_nations.xlsx','total wealth, 1995');
raw = raw(7:215,2:21);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,2,3]);
raw = raw(:,[4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Code = cellVectors(:,1);
Region = cellVectors(:,2);
IncomeGr = cellVectors(:,3);
Population = data(:,1);
TotalWealth = data(:,2);
IntangibleCapital = data(:,3);
NetForeignAssets = data(:,4);
ProducedCapital = data(:,5);
NaturalCapital = data(:,6);
Crop = data(:,7);
PastureLand = data(:,8);
ForestTimber = data(:,9);
ForestNTF = data(:,10);
ProtectedAreas = data(:,11);
Oil = data(:,12);
NaturalGas = data(:,13);
Hardcoal = data(:,14);
Softcoal = data(:,15);
Minerals = data(:,16);
SubsoilAssets = data(:,17);

% test plot


%% Clear temporary variables
% clearvars data raw cellVectors R;