%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /home/atomic/git/COGS109_Final/scripts/total_and_per_capita_wealth_of_nations.xlsx
%    Worksheet: total wealth, 2000
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/11/25 12:22:32

clear;
%% Import the data
[~, ~, raw] = xlsread('total_and_per_capita_wealth_of_nations.xlsx','total wealth, 2000');
raw = raw(7:215,2:21);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,2,3]);
raw = raw(:,[4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
Code1 = cellVectors(:,1);
Region1 = cellVectors(:,2);
IncomeGr1 = cellVectors(:,3);
Population1 = data(:,1);
TotalWealth1 = data(:,2);
IntangibleCapital1 = data(:,3);
NetForeignAssets1 = data(:,4);
ProducedCapital1 = data(:,5);
NaturalCapital1 = data(:,6);
Crop1 = data(:,7);
PastureLand1 = data(:,8);
ForestTimber1 = data(:,9);
ForestNTF1 = data(:,10);
ProtectedAreas1 = data(:,11);
Oil1 = data(:,12);
NaturalGas1 = data(:,13);
Hardcoal1 = data(:,14);
Softcoal1 = data(:,15);
Minerals1 = data(:,16);
SubsoilAssets1 = data(:,17);

%% Clear temporary variables
clearvars data raw cellVectors R;